name: money_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.1.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  math_expressions: ^2.4.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  build_runner: ^2.4.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.1
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/
    - assets/catagorysvg/
